// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlwnxdqhdqmzjcfvrakw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsd254ZHFoZHFtempjZnZyYWt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMzE0OTIsImV4cCI6MjA2NzYwNzQ5Mn0.mkS8I4vYSzhPO990Sw_Vi83GBbPUvi74hyBZljQY1Aw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});